name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Cache npm packages
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      # apparently the action doesn't support specifying where the recipe is
      - name: Prepare deployment
        run: cp deploy/deploy.php .

      - name: Deploy using deployer
        uses: deployphp/action@v1
        with:
          dep: deploy
          private-key: ${{ secrets.DEPLOYER_SSH_KEY }}
